### ISSUE TITLE
Wamp Xampp and others...

### ISSUE THREAD

**Issue by amdad** [COCOPi/copilot#3]
I cannot run Blog pages on any of Windows Apache software.
I guess I'm missing some path/s config or there is something in copilot that can be improved to support it better?

![error](https://cloud.githubusercontent.com/assets/10062429/7549447/2963bf9c-f635-11e4-9c5e-231ae77e91fa.png)

**Comment by florianletsch** [comment]
Looks like an issue with windows paths. Thanks for reporting, we'll look into it.
